version: '3.8'
services:
  app-spring-restfull:
    image: volverinejr/app-spring-restfull
    restart: always
    build: ./CrudPessoa
    working_dir: /CrudPessoa
    environment:
      TZ: America/Bahia
      SPRING_BOOT_ENVIRONMENT: Production
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    networks:
      - miro-network
networks:
    miro-network:
        driver: bridge