version: '3.4'
services:
  db:
    image: volverinejr/mysql-app-spring-restfull
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Bahia
      MYSQL_ROOT_PASSWORD: miro123456
      MYSQL_USER: miroroot
      MYSQL_PASSWORD: miro123456
      MYSQL_DATABASE: db_spring_docker
    ports:
      - "3308:3306"
    networks:
      - miro-network
  app-spring-restfull:
    image: volverinejr/app-spring-restfull
    restart: always
    build: ./CrudPessoa
    working_dir: /CrudPessoa
    environment:
      TZ: America/Bahia
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./CrudPessoa:/CrudPessoa
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - miro-network
networks:
    miro-network:
        driver: bridge